apiVersion: v1
kind: Service
metadata:
  name: log-out-svc
spec:
  type: ClusterIP
  selector:
    app: log-out # This is the app as declared in the deployment.
  ports:
    - port: 2344 
      targetPort: 3008 # This is the target port in our deploy