apiVersion: v1
kind: Service
metadata:
  name: dwk-project-svc
spec:
  type: ClusterIP
  selector:
    app: dwk-project # This is the app as declared in the deployment.
  ports:
    - port: 2345 
      targetPort: 3008 # This is the target port in our deploy