apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-out
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-out
  template:
    metadata:
      labels:
        app: log-out
    spec:
      containers:
        - name: dwk-project
          image: salvahappydev/log-out:2.0.0
          env:
          - name: PORT
            value: "3008"